name: 'segment'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
    vars:
        #location of raw data table
        segment_page_views_table: "rakam_land.pages"
        
        # number of trailing hours to re-sessionize for. 
        # events can come in late and we want to still be able to incorporate 
        # them into the definition of a session without needing a full refresh.
        segment_sessionization_trailing_window: 3 
